### ISSUE TITLE
AX650 compilation error

### ISSUE THREAD

**Issue by sagar1899** [AXERA-TECH/ax-pipeline#112]
Hi,
while building pipeline for AX650 using **cmake -DAXERA_TARGET_CHIP=AX650 -DBSP_MSP_DIR="/home/sagarkhimani/Downloads/2.Pulsar/ax-pipeline/ax650n_bsp_sdk/msp/out" -DOpenCV_DIR="/home/sagarkhimani/Downloads/2.Pulsar/ax-pipeline/3rdparty/libopencv-4.5.5-aarch64/lib/cmake/opencv4" -DSIPY_BUILD=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="/home/sagarkhimani/Downloads/2.Pulsar/ax-pipeline/toolchains/aarch64-none-linux-gnu.toolchain.cmake" -DCMAKE_INSTALL_PREFIX=install ..** and make install, i'm getting below error.

sagarkhimani@sagarkhimani:~/Downloads/2.Pulsar/ax-pipeline/build$ make install
[ 23%] Built target rtspclisvr
[ 46%] Built target RtspServer
[ 47%] Built target rtsp_h264_file
[ 48%] Built target rtsp_pusher
[ 50%] Built target rtsp_server
[ 54%] Built target ByteTrack
[ 55%] Built target Mp4Demuxer
[ 59%] Built target common_pipeline
[ 68%] Built target axdl
[ 69%] Linking CXX executable sample_demux_ivps_npu_rtsp
/home/sagarkhimani/Downloads/2.Pulsar/ax-pipeline/3rdparty/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/9.2.1/../../../../aarch64-none-linux-gnu/bin/ld: cannot find -ldrm
collect2: error: ld returned 1 exit status
make[2]: *** [examples/sample_demux_ivps_npu_rtsp/CMakeFiles/sample_demux_ivps_npu_rtsp.dir/build.make:167: examples/sample_demux_ivps_npu_rtsp/sample_demux_ivps_npu_rtsp] Error 1
make[1]: *** [CMakeFiles/Makefile2:577: examples/sample_demux_ivps_npu_rtsp/CMakeFiles/sample_demux_ivps_npu_rtsp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
![Uploading Screenshot from 2024-03-19 14-14-06.png…]()

**Comment by K-tang-mkv** [comment]
@sagar1899 I got the same error as you, but the official steps are totally right, make sure every step right! 
I got this error because I didn't follow the official step. In the cross-compile [step 2.2](https://github.com/AXERA-TECH/ax-pipeline/blob/main/docs/compile_650.md#22-%E5%87%86%E5%A4%87%E5%AD%90%E6%A8%A1%E5%9D%97), I didn't `cd ax650n_bsp_sdk`, and then I just `mkdir third-party` under the folder ax-pipeline so that compile failing at the final.
