### ISSUE TITLE
New camera support

### ISSUE THREAD

**Issue by eljuguetero** [AXERA-TECH/ax-pipeline#46]
Hi,

I already have an AXera-Pi kit, it's a very interesting piece of hardware. 

I'm working on a device base on AXera device, but I need to add a new image sensor, what should be the way? How can I access the Linux kernel source? Where should I be asking this question, I think this is not the right channel.
BR

**Comment by junhuanchen** [comment]
As the New Year approaches, we will be a little busy. As for the new camera support, you can choose the USB camera of V4L2 here.

Because mipi camera has not been reviewed to open source, USB camera can be used.

-  https://wiki.sipeed.com/hardware/zh/maixIII/ax-pi/basic_usage.html#%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE-USB-HOST-%E8%AF% BB%E5%8F%96%E4%B8%80%E4%B8%AA-USB-%E6%91%84%E5%83%8F%E5%A4%B4

- https://github.com/AXERA-TECH/ax-pipeline/tree/main/examples/sample_v4l2_user_ivps_joint_vo

- https://github.com/junhuanchen/ax-pipeline-api

We are already translating some Chinese content into English.
